version: '3'

services:
  app:
    build: .
    container_name: sigfis_api
    entrypoint: dockerize -template ./.docker/app/.env:.env -wait tcp://db:5432 -timeout 40s ./.docker/app/entrypoint.sh
    tty: true
    restart: always
    environment:
      - DB_HOST=db
      - DB_DATABASE=sigfis
      - DB_USERNAME=postgres
      - DB_PASSWORD=postgres
    ports:
      - "5000:5000"
    volumes:
      - .:/usr/src/app
    networks:
      - app-network
    depends_on:
      - db

  db:
    image: mdillon/postgis:11
    container_name: sigfis_db
    tty: true
    environment:
      - POSTGRES_DB=sigfis
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
    ports:
      - '5434:5432'
    volumes:
      - sigfis-postgresql:/var/lib/postgresql/data
    networks:
      - app-network

  pgadmin:
    image: dpage/pgadmin4
    container_name: sigfis_pgadmin
    tty: true
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@sigfis.com
      - PGADMIN_DEFAULT_PASSWORD=123456
    ports:
      - '9000:80'
    volumes:
      - sigfis-pgadmin:/var/lib/pgadmin
    networks:
      - app-network

volumes:
  sigfis-postgresql:
    driver: local
  sigfis-pgadmin:
    driver: local

networks:
  app-network:
    driver: bridge
